security:
    providers:
        users:
            entity: { class: App\Entity\User, property: username }
        admin:
            entity: { class: App\Entity\Admin, property: username }
    encoders:
        App\Entity\User:
            algorithm: argon2i
            memory_cost: 16384
            time_cost: 2
            threads: 4
        App\Entity\Admin:
            algorithm: argon2i
            memory_cost: 16384
            time_cost: 2
            threads: 4
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: ^/admin
            provider: admin
            anonymous: ~
            logout:
                invalidate_session: true
                path: /admin/logout
                target: /
            guard:
                authenticators:
                    - App\Security\Guard\AdminAuthenticator
        middle:
            pattern: ^/(user|api)
            provider: users
            anonymous: ~
            logout:
                invalidate_session: true
                path: /user/logout
                target: /user
            guard:
                authenticators:
                    - App\Security\Guard\UserAuthenticator
    access_control:
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_SUPER_ADMIN }
        - { path: ^/user/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/password/request$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/password/reset/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user, roles: ROLE_USER }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
